// Roamvas service worker — deliberately hand-written rather than generated by a
// build plugin, so it has no dependency on knowing Vite's hashed output
// filenames ahead of time (those change every build). Instead of a static
// precache list, it caches same-origin GET requests opportunistically as the
// app is used ("stale while revalidate"), which is enough to make a
// previously-visited trip fully usable offline — the trip data itself
// already lives in localStorage regardless of the network.
//
// Bump this on any change that should force clients to pick up a fresh
// cache (e.g. after a deploy where old cached assets could otherwise linger).
const CACHE_NAME = 'roamvas-cache-v1';

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(['./', './index.html'])).catch(() => {})
  );
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;

  // Only handle simple same-origin GETs. Everything else (AI provider
  // calls, Wikipedia photo lookups, Google Fonts, Google Maps links, and
  // any non-GET request) passes straight through to the network untouched —
  // those inherently need connectivity and shouldn't be cached or faked.
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    caches.match(request).then((cached) => {
      const network = fetch(request)
        .then((response) => {
          if (response && response.ok) {
            const copy = response.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(request, copy)).catch(() => {});
          }
          return response;
        })
        .catch(() => cached);
      // Serve from cache immediately when we have it (fast, and works
      // offline); refresh the cache in the background for next time.
      return cached || network;
    })
  );
});
